language: node_js
node_js:
  - 12 # use nodejs v12 LTS
cache: npm
branches:
  only:
    - source # build master branch only
install:
  - npm install
script:
  - cp -r blogs .vuepress/public
  - npm run build # generate static files
  - bash deploy.sh $GH_TOKEN
