sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - source # build master branch only
script:
  - cp -r source/_posts/. source
  - hexo generate # generate static files
deploy:
  provider: script
  script: bash deploy.sh $GH_TOKEN
  on:
    branch: master