language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - source # build master branch only
install:
  - npm install
  - npm install hexo-deployer-git --save
script:
  - cp -r source/_posts/. source
  - hexo generate # generate static files
  - bash deploy.sh $GH_TOKEN
